### ISSUE TITLE
Error: spawn ENOENT with node v0.10.2

### ISSUE THREAD

**Issue by kvbik** [nathanboktae/mocha-phantomjs#53]
hey,

i have a testsuite that works on mac os box with node `v0.8.20` . my box is archlinux with node `v0.10.2` a it fails. even this simple example does not work:

```
$ ./bin/mocha-phantomjs ./test/bad.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:948:11)
    at Process.ChildProcess._handle.onexit (child_process.js:739:34)
```

it looks like i am not the only one [1], who gets error like this

[1] http://net.tutsplus.com/tutorials/javascript-ajax/testing-javascript-with-phantomjs/#comment-829198059

maybe it is connected to some node internals [2], but i am not sure..

[2] https://github.com/joyent/node/issues/4674

**Comment by haledeng** [comment]
In my case, add a `.cmd`  extension to `mocha-phantonjs`, which like:
```
spawn('mocha-phantomjs.cmd', ['xxx.html', '-R', 'json'])
```
